### ISSUE TITLE
Provide prominent confirmation to user when an offer has successfully been added / created.

### ISSUE THREAD

**Issue by ItsEcholot** [hexcodech/booki-frontend#9]

**Comment by Tyratox** [comment]
How should this look like?

**Comment by ItsEcholot** [comment]
Maybe modal with a green checkbox or something along these lines. Could also be done with a notification in the top right corner.

**Comment by Tyratox** [comment]
If a notification is enough, we should probably set them at least to position fixed, otherwise it can easily be missed if the user scrolled on the page ^^. A modal would also be possible but I'm not sure if it is too much? Maybe also redirect the user to /profile so he/she can see that the offer has been created. (After #10 is fixed)

**Comment by ItsEcholot** [comment]
Yeah you're probably right. A modal would be too much. Notification would work if it's fixed and doesn't hide automatically.

**Comment by chdabre** [comment]
I'd like a modal. Notification is OK for a beta but in a production version a modal would look more polished. Maybe make the dialog end with an animation and auto-hide?

**Comment by Tyratox** [comment]
Should *all* notifications be like modals?

**Comment by chdabre** [comment]
DONT

**Comment by Tyratox** [comment]
Why? If user feedback is needed, then it should always be the same way. If we differentiate between two types, one of them probably is unnecessary. Also we could just use the existing modal component in order to stack the notifications (if needed)?

Another option would be for example to redirect to /profile and highlight the created offer for a few seconds. The problem here is that we probably also have to scroll because it doesn't have to be on the top of the page (especially on mobile).

**Comment by chdabre** [comment]
Great Idea for the second option. When I said modal i thought more of a simple checkmark at the end of the progress without requesting user confirmation… which wouldnt make sense for other notifications.

**Comment by Tyratox** [comment]
Feedback? Can I close this issue?

**Comment by ItsEcholot** [comment]
Redirect didn't work for me. Sounds like a good solution tough.

**Comment by Tyratox** [comment]
Are you sure? I just tested it once more and for me it worked? Browser cache?

**Comment by ItsEcholot** [comment]
Works after additional testing
